### ISSUE TITLE
500 cheminventory/chemical/add 

### ISSUE THREAD

**Issue by Graf-Zahl** [nano-bio/labbooks#21]
```
Internal Server Error: /admin/cheminventory/chemical/add/

OSError at /admin/cheminventory/chemical/add/
No exception message supplied

Request Method: POST
Request URL: http://c744-labbooks.uibk.ac.at/admin/cheminventory/chemical/add/?_to_field=id&_popup=1
Django Version: 3.2.17
Python Executable: /usr/local/bin/python
Python Version: 3.9.16
Python Path: ['/src', '/usr/local/bin', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/site-packages', '/var/opt/', '/var/opt/', '/var/opt', '/var/opt']
Server time: Thu, 03 Aug 2023 16:55:12 +0200
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'crispy_forms',
 'crispy_bootstrap5',
 'ckeditor',
 'django_crontab',
 'cheminventory',
 'journal',
 'labinventory',
 'massspectra',
 'mscpimporter',
 'clustof',
 'nanoparticles',
 'pulsetube',
 'surftof',
 'snowball',
 'toffy',
 'toffy2',
 'vg',
 'wippi']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fitlib/helplib.py", line 17, in openfile
    f = open(filename, rw)

During handling of the above exception ([Errno 2] No such file or directory: 'chemspider_token.txt'), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/fitlib/helplib.py", line 23, in openfile
    f = open(filename, rw)

During handling of the above exception ([Errno 2] No such file or directory: '/usr/local/bin/chemspider_token.txt'), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/fitlib/chemlib.py", line 44, in __init__
    f = hl.openfile('chemspider_token.txt')
  File "/usr/local/lib/python3.9/site-packages/fitlib/helplib.py", line 27, in openfile
    raise IOError('Could not read file')

During handling of the above exception (Could not read file), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1579, in _changeform_view
    form_validated = form.is_valid()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 374, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/models.py", line 413, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1236, in full_clean
    self.clean()
  File "/src/cheminventory/models.py", line 154, in clean
    chemobj = fitlib.chemlib.ChemicalObject(name=self.name, inchi=self.inchi, inchikey=self.inchikey,
  File "/usr/local/lib/python3.9/site-packages/fitlib/chemlib.py", line 46, in __init__
    raise IOError

Exception Type: OSError at /admin/cheminventory/chemical/add/

Request information:
USER: AnnaMaria

```

**Comment by Graf-Zahl** [comment]
@Mandolorijan bitte Beschreibung hinzufuegen, unter welchen Umstaenden der Fehler auftritt.

**Comment by Mandolorijan** [comment]
Wenn man im Administrator Menü unter Cheminventory/Chemicals Chemikalien hinzufügen möchte ('Add Chemicals +') und dann speichern will, tritt dieser Error ('Server Error (500)') auf.
